In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [6]:
df = pd.read_csv("loan approval data.csv")
df.head()
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Applicant_ID        950 non-null    float64
 1   Applicant_Income    950 non-null    float64
 2   Coapplicant_Income  950 non-null    float64
 3   Employment_Status   950 non-null    object
 4   Age                 950 non-null    float64
 5   Marital_Status      950 non-null    object
 6   Dependents          950 non-null    float64
 7   Credit_Score        950 non-null    float64
 8   Existing_Loans      950 non-null    float64
 9   DTI_Ratio           950 non-null    float64
 10  Savings             950 non-null    float64
 11  Collateral_Value    950 non-null    float64
 12  Loan_Amount         950 non-null    float64
 13  Loan_Term           950 non-null    float64
 14  Loan_Purpose        950 non-null    object
 15  Property_Area       950 non-null    object
 16  Education_Level     950 non-null    object
 17  Gender              950 non-null    object
 18  Employer_Category   950 non-null    object
 19  Loan_Approved       950 non-null    object
dtypes: float64(12), object(8)
memory usage: 156.4+ KB

Applicant_ID          50
Applicant_Income      50
Coapplicant_Income    50
Employment_Status     50
Age                   50
Marital_Status        50
Dependents            50
Credit_Score          50
Existing_Loans        50
DTI_Ratio             50
Savings               50
Collateral_Value      50
Loan_Amount           50
Loan_Term             50
Loan_Purpose          50
Property_Area         50
Education_Level       50
Gender                50
Employer_Category     50
Loan_Approved         50
dtype: int64

In [7]:
categotical_col = df.select_dtypes(include=["object"]).columns
numerical_col = df.select_dtypes(include=["float64"]).columns

In [12]:
from sklearn.impute import SimpleImputer
num_imp = SimpleImputer(strategy="mean")
df[numerical_col] = num_imp.fit_transform(df[numerical_col])

In [13]:
df.head()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2.0,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,48.0,Car,Semiurban,Graduate,NaN,Private,No
2,3.0,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,NaN,Urban,NaN,Female,Government,Yes
3,4.0,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,5.0,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,NaN,Graduate,Male,Private,Yes

In [14]:
cat_imp = SimpleImputer(strategy="most_frequent")
df[categotical_col] = cat_imp.fit_transform(df[categotical_col])
df.isnull().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Applicant_ID        1000 non-null   float64
 1   Applicant_Income    1000 non-null   float64
 2   Coapplicant_Income  1000 non-null   float64
 3   Employment_Status   1000 non-null   object
 4   Age                 1000 non-null   float64
 5   Marital_Status      1000 non-null   object
 6   Dependents          1000 non-null   float64
 7   Credit_Score        1000 non-null   float64
 8   Existing_Loans      1000 non-null   float64
 9   DTI_Ratio           1000 non-null   float64
 10  Savings             1000 non-null   float64
 11  Collateral_Value    1000 non-null   float64
 12  Loan_Amount         1000 non-null   float64
 13  Loan_Term           1000 non-null   float64
 14  Loan_Purpose        1000 non-null   object
 15  Property_Area       1000 non-null   object
 16  Education_Level     1000 non-null   object
 17  Gender              1000 non-null   object
 18  Employer_Category   1000 non-null   object
 19  Loan_Approved       1000 non-null   object
dtypes: float64(12), object(8)
memory usage: 156.4+ KB

In [15]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le = LabelEncoder()

df["Education_Level"] = le.fit_transform(df["Education_Level"])
df["Loan_Approved"] = le.fit_transform(df["Loan_Approved"])
df["Marital_Status"] = le.fit_transform(df["Marital_Status"])
df["Employer_Category"] = le.fit_transform(df["Employer_Category"])

In [16]:
cols = ["Employment_Status","Loan_Purpose","Property_Area","Gender"]
oha = OneHotEncoder(drop="first",sparse_output=False,handle_unknown="ignore")
encoderd = oha.fit_transform(df[cols])
encoderd_df=pd.DataFrame(encoderd,columns=oha.get_feature_names_out(cols),index=df.index)
df=pd.concat([df.drop(columns=cols),encoderd_df],axis=1)

In [17]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Applicant_ID                     1000 non-null   float64
 1   Applicant_Income                 1000 non-null   float64
 2   Coapplicant_Income               1000 non-null   float64
 3   Age                              1000 non-null   float64
 4   Marital_Status                   1000 non-null   int64
 5   Dependents                       1000 non-null   float64
 6   Credit_Score                     1000 non-null   float64
 7   Existing_Loans                   1000 non-null   float64
 8   DTI_Ratio                        1000 non-null   float64
 9   Savings                          1000 non-null   float64
 10  Collateral_Value                 1000 non-null   float64
 11  Loan_Amount                      1000 non-null   float64
 12  Loan_Term                        1000 non-null   float64
 13  Education_Level                  1000 non-null   int64
 14  Employer_Category                1000 non-null   int64
 15  Loan_Approved                    1000 non-null   int64
 16  Employment_Status_Salaried       1000 non-null   float64
 17  Employment_Status_Self-employed  1000 non-null   float64
 18  Employment_Status_Unemployed     1000 non-null   float64
 19  Loan_Purpose_Car                 1000 non-null   float64
 20  Loan_Purpose_Education           1000 non-null   float64
 21  Loan_Purpose_Home                1000 non-null   float64
 22  Loan_Purpose_Personal            1000 non-null   float64
 23  Property_Area_Semiurban          1000 non-null   float64
 24  Property_Area_Urban              1000 non-null   float64
 25  Gender_Male                      1000 non-null   float64
dtypes: float64(22), int64(4)
memory usage: 203.3 KB

In [19]:
X = df.drop('Loan_Approved',axis=1)
y = df['Loan_Approved']

,Applicant_ID,Applicant_Income,Coapplicant_Income,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,...,Employment_Status_Salaried,Employment_Status_Self-employed,Employment_Status_Unemployed,Loan_Purpose_Car,Loan_Purpose_Education,Loan_Purpose_Home,Loan_Purpose_Personal,Property_Area_Semiurban,Property_Area_Urban,Gender_Male
0,1.0,17795.0,1387.0,51.0,0,0.0,637.0,4.0,0.53,19403.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,2.0,2860.0,2679.0,46.0,0,3.0,621.0,2.0,0.30,2580.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
2,3.0,7390.0,2106.0,25.0,1,2.0,674.0,4.0,0.20,13844.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,4.0,13964.0,8173.0,40.0,0,2.0,579.0,3.0,0.31,9553.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5.0,13284.0,4223.0,31.0,1,2.0,721.0,1.0,0.29,9386.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0

In [21]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

,Applicant_ID,Applicant_Income,Coapplicant_Income,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,...,Employment_Status_Salaried,Employment_Status_Self-employed,Employment_Status_Unemployed,Loan_Purpose_Car,Loan_Purpose_Education,Loan_Purpose_Home,Loan_Purpose_Personal,Property_Area_Semiurban,Property_Area_Urban,Gender_Male
29,30.00,5890.000000,8041.0,31.000000,0,0.000000,603.000000,0.000000,0.110000,11906.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
535,536.00,4779.000000,529.0,50.000000,0,0.000000,614.000000,0.000000,0.210000,5369.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
695,696.00,10852.571579,8927.0,36.000000,0,0.000000,584.000000,4.000000,0.220000,3186.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
557,558.00,2384.000000,2113.0,39.971579,0,1.000000,726.000000,4.000000,0.340000,11882.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
836,837.00,5228.000000,5249.0,42.000000,1,1.000000,676.033684,1.950526,0.180000,17669.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107.00,10755.000000,4107.0,59.000000,0,0.000000,560.000000,2.000000,0.347263,6806.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
270,271.00,2569.000000,5068.0,39.971579,0,1.474737,673.000000,1.000000,0.530000,3563.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
860,861.00,9783.000000,6099.0,31.000000,1,0.000000,703.000000,1.000000,0.347263,2575.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
435,501.22,16512.000000,3762.0,53.000000,0,1.000000,616.000000,1.000000,0.320000,14780.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
102,103.00,2206.000000,5136.0,40.000000,1,0.000000,634.000000,1.000000,0.350000,11590.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0

In [30]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

array([[-1.66336551, -1.01234556,  1.02716377, ..., -0.48038446,
        -1.05395348, -1.29444401],
       [ 0.1281584 , -1.23639141, -1.59187898, ..., -0.48038446,
         0.94880848,  0.77253245],
       [ 0.69464817, -0.01158625,  1.33606578, ...,  2.081666  ,
        -1.05395348,  0.77253245],
       ...,
       [ 1.27884075, -0.22727759,  0.35008962, ..., -0.48038446,
        -1.05395348,  0.77253245],
       [ 0.00501768,  1.12970221, -0.46470044, ..., -0.48038446,
        -1.05395348,  0.77253245],
       [-1.40490455, -1.75526629,  0.01434173, ..., -0.48038446,
         0.94880848,  0.77253245]], shape=(800, 25))

In [34]:
#logistic regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train_scaler,y_train)
y_pred = lr.predict(X_test_scaler)

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0])

In [40]:
# model evolution
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
print("confusion matrix:",confusion_matrix(y_test,y_pred))
print("accuracy_score:",accuracy_score(y_test,y_pred))
print("precision_score:",precision_score(y_test,y_pred))
print("recall_score:",recall_score(y_test,y_pred))
print("f1_score:",f1_score(y_test,y_pred))

confusion matrix: [[129  10]
 [ 13  48]]
accuracy_score: 0.885
precision_score: 0.8275862068965517
recall_score: 0.7868852459016393
f1_score: 0.8067226890756303

In [53]:
# knn 
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train_scaler,y_train)
y_pred = knn.predict(X_test_scaler)
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
print("confusion matrix:",confusion_matrix(y_test,y_pred))
print("accuracy_score:",accuracy_score(y_test,y_pred))
print("precision_score:",precision_score(y_test,y_pred))
print("recall_score:",recall_score(y_test,y_pred))
print("f1_score:",f1_score(y_test,y_pred))

confusion matrix: [[124  15]
 [ 28  33]]
accuracy_score: 0.785
precision_score: 0.6875
recall_score: 0.5409836065573771
f1_score: 0.6055045871559633

In [50]:
# naive bayes
from sklearn.naive_bayes import GaussianNB
nb_model= GaussianNB()
nb_model.fit(X_train_scaler,y_train)
y_pred = nb_model.predict(X_test_scaler)

from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
print("confusion matrix:",confusion_matrix(y_test,y_pred))
print("accuracy_score:",accuracy_score(y_test,y_pred))
print("precision_score:",precision_score(y_test,y_pred))
print("recall_score:",recall_score(y_test,y_pred))
print("f1_score:",f1_score(y_test,y_pred))

confusion matrix: [[128  11]
 [ 16  45]]
accuracy_score: 0.865
precision_score: 0.8035714285714286
recall_score: 0.7377049180327869
f1_score: 0.7692307692307693